## Filter by multiple index and columns

### Specific values

```python
df.loc[index,column]
```

**Exercise**: Filer by month 7 and `Eolic` technology.

In [ ]:
df = df_energy.pivot_table(index=['month', 'hour'], columns='technology', values='generation_mwh', aggfunc='sum')
df

technology    Carbon  Cogeneration  Combined Cycle  Domestic Residuals  \
month hour
1     0     179108.5      304463.3        242808.6             14362.3
      1     165583.8      302752.6        207180.5             14385.6
      2     156947.0      301420.6        189723.9             14314.6
      3     150282.9      300897.8        184386.3             14350.1
      4     148771.4      300417.5        186017.6             14273.4
...              ...           ...             ...                 ...
12    19     59398.5      295974.1        520166.4             17071.4
      20     58805.9      295938.7        514276.3             17076.6
      21     57876.7      295149.5        497094.4             17105.4
      22     56613.6      293084.1        467496.2             17110.2
      23     55156.2      289080.5        411775.0             17146.4

technology     Eolic  Hydraulic No UGH  Hydraulic UGH  \
month hour
1     0     735732.3           70261.0       279969.5
      1     731772.9           68817.5       244351.5
      2     731486.1           67495.6       215892.0
      3     726470.7           66861.4       204314.0
      4     728539.2           66646.8       201602.2
...              ...               ...            ...
12    19    853163.5           85457.6       479135.1
      20    861893.1           85758.8       476101.0
      21    866431.0           83970.1       440138.0
      22    865322.0           81710.1       390377.5
      23    857028.2           80400.3       336974.5

technology  Non-renewable Residuals   Nuclear  Other Renewables  \
month hour
1     0                     29471.3  647159.8           43499.7
      1                     29392.2  646718.0           43317.8
      2                     29242.4  646116.1           43242.1
      3                     29255.0  645804.1           43030.0
      4                     29211.5  646026.6           42954.6
...                             ...       ...               ...
12    19                    29952.2  566571.6           50129.7
      20                    29873.4  566605.7           49975.4
      21                    29856.6  566946.5           49974.7
      22                    29841.8  567069.4           49702.0
      23                    29851.5  567698.4           49378.5

technology  Other Residuals  Photovoltaic Solar  Photovoltaic Thermal  \
month hour
1     0             11573.5                55.7                 907.7
      1             11505.2                23.3                 808.8
      2             11439.7                32.8                 720.9
      3             11447.6                24.6                 624.8
      4             11481.6               103.5                 588.3
...                     ...                 ...                   ...
12    19             9559.5               734.4                1406.8
      20             9553.3               375.6                1084.4
      21             9508.2               292.2                 876.8
      22             9489.5               230.2                 735.2
      23             9462.9               203.4                 696.1

technology  Pumping Turbine  Total Exports  Total Imports
month hour
1     0              5336.4      -151103.3       224079.6
      1              1504.5      -204030.0       214024.4
      2                45.0      -225447.7       208475.5
      3                45.0      -226559.4       212692.1
      4                 0.0      -236293.3       220862.8
...                     ...            ...            ...
12    19            98055.6      -215046.5       255875.9
      20            89037.3      -209814.3       279339.8
      21            63359.5      -194938.4       281095.0
      22            47234.6      -228442.5       222205.6
      23            28243.9      -270203.3       179505.9

[288 rows x 16 columns]

In [ ]:
df.loc[(7,14), 'Eolic']

384314.6

In [ ]:
df.loc[7,14:, :'Eolic']

UnsortedIndexError: 'MultiIndex slicing requires the index to be lexsorted: slicing on levels [1, 2], lexsort depth 2'

In [ ]:
df.loc[7,'Eolic']

11252965.2

### Slices

```python
df.loc[index:, :column]
```

**Exercise**: Filter from month 7 to the end and from the beginning to `Eolic` technology.

In [ ]:
df.loc[7:,:'Eolic']

technology,Carbon,Cogeneration,Combined Cycle,Domestic Residuals,Eolic
month,,,,,
7,1295716.7,7121353.7,16098784.3,350329.9,11252965.2
8,1039752.8,6732834.2,15600664.3,414946.6,9833109.2
9,1237824.3,6875012.2,14444281.3,354067.6,10990583.7
10,1468222.6,7022052.0,12336734.7,372724.3,13739439.9
11,1485812.2,7061207.4,12951110.4,387585.5,18035235.7
12,1357028.7,6889407.9,9875061.1,409984.9,19904095.9